local colors = require("plugins/theme/colors").getColors()

local M = {
	TSError = { bg = colors.red },
	MoreMsg = { bg = colors.debug },
	Pmenu = { fg = colors.debug, bg = colors.debug },
	TSConstMacro = { bg = colors.red },
	TSConstructor = { fg = colors.red },
	TSField = { fg = colors.red },
	TSFloat = { fg = colors.red, style = "bold" },
	TSFuncBuiltin = { fg = colors.red },
	TSFuncMacro = { fg = colors.red },
	TSInclude = { fg = colors.red },
	TSKeywordFunction = { fg = colors.red, style = "italic" },
	TSKeywordOperator = { fg = colors.red, style = "italic" },
	TSKeywordReturn = { fg = colors.red, style = "bold" },
	TSAttribute = { fg = colors.red },
	TSLabel = { fg = colors.red },
	TSMethod = { fg = colors.red },
	TSNamespace = { fg = colors.red },
	TSNone = { fg = colors.red },
	TSOperator = { fg = colors.red },
	TSParameter = { fg = colors.red },
	TSParameterReference = { fg = colors.red },
	TSProperty = { fg = colors.red },
	TSPunctDelimiter = { fg = colors.red },
	TSPunctBracket = { fg = colors.red },
	TSPunctSpecial = { fg = colors.red },
	TSRepeat = { fg = colors.red },
	TSStringEscape = { fg = colors.red },
	TSSymbol = { fg = colors.red },
	TSTag = { fg = colors.red },
	TSTagDelimiter = { fg = colors.red },
	TSText = { fg = colors.red },
	TSStrong = { fg = colors.red },
	TSEmphasis = { fg = colors.red },
	TSUnderline = { fg = colors.red },
	TSStrike = { fg = colors.red },
	TSTitle = { fg = colors.red },
	TSLiteral = { fg = colors.red },
	TSURI = { fg = colors.red },
	TSMath = { fg = colors.red },
	TSTextReference = { fg = colors.red },
	TSEnvironment = { fg = colors.red },
	TSEnvironmentName = { fg = colors.red },
	TSNote = { fg = colors.red },
	TSWarning = { fg = colors.red },
	TSDanger = { fg = colors.red },
	TSTypeBuiltin = { fg = colors.red },
	TSVariableBuiltin = { fg = colors.red },
	ErrorMsg = { fg = colors.debug },
	FoldColumn = { fg = colors.debug },
	Folded = { fg = colors.debug },
	Question = { fg = colors.debug },
	SpecialKey = { fg = colors.debug },
	Substitute = { fg = colors.debug },
	TabLine = { fg = colors.debug },
	TabLineFill = { fg = colors.debug },
	TabLineSel = { fg = colors.debug },
	WarningMsg = { fg = colors.debug },
	WildMenu = { fg = colors.debug },
	Ignore = { fg = colors.debug },
	ToolbarLine = { fg = colors.debug },
	ToolbarButton = { fg = colors.debug },
	qfLineNr = { fg = colors.debug },
	PmenuSelBold = { fg = colors.debug },
	NormalFloat = { fg = colors.debug },
	QuickFixLine = { fg = colors.debug },
	Debug = { fg = colors.debug },
	debugBreakpoint = { fg = colors.debug },
	PreCondit = { fg = colors.debug },
	Typedef = { fg = colors.debug },
}

return M
