local M = {
	Bold = { link = "TSStrong" },
	Boolean = { link = "TSBoolean" },
	Character = { link = "TSCharacter" },
	Comment = { link = "TSComment" },
	Conditional = { link = "TSConditional" },
	Constant = { link = "TSConstant" },
	Define = { link = "TSConstBuiltin" },
	Delimiter = { link = "TSPunctDelimiter" },
	Error = { link = "TSError" },
	Exception = { link = "TSException" },
	Float = { link = "TSFloat" },
	Function = { link = "TSFunction" },
	Identifier = { link = "TSVariable" },
	Include = { link = "TSInclude" },
	Italic = { link = "TSEmphasis" },
	Keyword = { link = "TSKeyword" },
	Label = { link = "TSLabel" },
	Macro = { link = "TSFuncMacro" },
	Number = { link = "TSNumber" },
	Operator = { link = "TSOperator" },
	Repeat = { link = "TSRepeat" },
	SpecialChar = { link = "TSStringEscape" },
	String = { link = "TSString" },
	Structure = { link = "TSAnnotation" },
	Field = { link = "TSProperty" },
	Tag = { link = "TSTag" },
	Title = { link = "TSTitle" },
	Type = { link = "TSType" },
	Underlined = { link = "TSUnderline" },
	asciidocAttributeEntry = { link = "TSAttribute" },
	cIncluded = { link = "TSConstructor" },
	healthError = { link = "TSDanger" },
	healthWarning = { link = "TSWarning" },
	rubySymbol = { link = "TSSymbol" },
	xmlNamespace = { link = "TSNamespace" },
}

return M
