local colors = require("plugins/theme/colors").getColors()

local M = {
	-- TODO вынести цвета ближе к настройкам плагинов
	-- TODO обозначить стандартные стили и к ним перелинковывать
		CocHighlightRead = { fg = colors.fg, bg = colors.bg3 },
		CocHighlightWrite = { fg = colors.fg, bg = colors.bg4 },
		CocMenu = { link = "Pmenu" },
		CocMenuSel = { link = "PmenuSel" },
		CocSearch = { fg = colors.fg4 },
		CocPumSearch = { link = "CocSearch" },
		CocSymbolDefault = { link = "CocSearch" },
		CocInfoFloat = { link = "CocSearch" },
		CocNotificationInfo = { link = "CocSearch" },
		CocNotificationProgress = { link = "CocSearch" },
		CocListSearch = { link = "CocSearch" },
		CocFloatActive = { link = "CocSearch" },
		CocMarkdownLink = { link = "CocSearch" },

		DashboardShortCut = { fg = colors.fg, bg = colors.bg },
		DashboardHeader = { fg = colors.fg, bg = colors.bg },
		DashboardCenter = { fg = colors.fg, bg = colors.bg },
		DashboardFooter = { fg = colors.fg, bg = colors.bg },

		ALEError = { fg = colors.red },
		ALEWarning = { fg = colors.yellow },
		ALEInfo = { fg = colors.fg5 },
		ALEErrorSign = { fg = colors.red },
		ALEWarningSign = { fg = colors.yellow },
		ALEInfoSign = { fg = colors.fg5 },

		DiffAdd = { fg = colors.fg4 },
		DiffChange = { fg = colors.fg5 },
		DiffDelete = { fg = colors.fg3 },
		DiffText = { fg = colors.fg5 },

		GitSignsAdd = { fg = colors.fg5 },
		GitSignsDelete = { fg = colors.fg4 },
		GitSignsChange = { fg = colors.fg5 },
		GitSignsChangeNr = { fg = colors.fg5 },
		GitSignsChangeLn = { fg = colors.fg5 },
		GitSignsChangeDelete = { fg = colors.fg4 },

		SignifySignAdd = { fg = colors.fg5 },
		SignifySignChange = { fg = colors.fg4 },
		SignifySignDelete = { fg = colors.fg3 },

		GitGutterAdd = { fg = colors.fg5 },
		GitGutterChange = { fg = colors.fg4 },
		GitGutterChangeDelete = { fg = colors.fg4 },
		GitGutterDelete = { fg = colors.fg3 },

		DiagnosticVirtualTextError = { fg = colors.red },
		DiagnosticVirtualTextWarn = { fg = colors.yellow },
		DiagnosticVirtualTextInfo = { fg = colors.fg5 },
		DiagnosticVirtualTextHint = { fg = colors.fg6 },
		DiagnosticSignError = { fg = colors.red },
		DiagnosticSignWarn = { fg = colors.yellow },
		DiagnosticSignInfo = { fg = colors.fg5 },
		DiagnosticSignHint = { fg = colors.fg6 },
		DiagnosticFloatingError = { fg = colors.red },
		DiagnosticFloatingWarn = { fg = colors.yellow },
		DiagnosticFloatingInfo = { fg = colors.fg5 },
		DiagnosticFloatingHint = { fg = colors.fg6 },
		DiagnosticUnderlineError = { style = "undercurl", sp = colors.red },
		DiagnosticUnderlineWarn = { style = "undercurl", sp = colors.yellow },
		DiagnosticUnderlineInfo = { style = "undercurl", sp = colors.fg5 },
		DiagnosticUnderlineHint = { style = "undercurl", sp = colors.fg6 },
		LspDiagnosticsVirtualTextError = { link = "DiagnosticVirtualTextError" },
		LspDiagnosticsSignError = { link = "DiagnosticSignError" },
		LspDiagnosticsFloatingError = { link = "DiagnosticFloatingError" },
		LspDiagnosticsVirtualTextWarning = { link = "DiagnosticVirtualTextWarn" },
		LspDiagnosticsSignWarning = { link = "DiagnosticSignWarn" },
		LspDiagnosticsFloatingWarning = { link = "DiagnosticFloatingWarn" },
		LspDiagnosticsVirtualTextInformation = { link = "DiagnosticVirtualTextInfo" },
		LspDiagnosticsSignInformation = { link = "DiagnosticSignInfo" },
		LspDiagnosticsFloatingInformation = { link = "DiagnosticFloatingInfo" },
		LspDiagnosticsVirtualTextHint = { link = "DiagnosticVirtualTextHint" },
		LspDiagnosticsSignHint = { link = "DiagnosticSignHint" },
		LspDiagnosticsFloatingHint = { link = "DiagnosticFloatingHint" },
		LspDiagnosticsUnderlineError = { link = "DiagnosticUnderlineError" },
		LspDiagnosticsUnderlineWarning = { link = "DiagnosticUnderlineWarn" },
		LspDiagnosticsUnderlineInformation = { link = "DiagnosticUnderlineInfo" },
		LspDiagnosticsUnderlineHint = { link = "DiagnosticUnderlineHint" },

		gitCommitBranch = {},
		gitCommitDiscardedFile = {},
		gitCommitDiscardedType = {},
		gitCommitHeader = {},
		gitCommitSelectedFile = {},
		gitCommitSelectedType = {},
		gitCommitUntrackedFile = {},
		gitEmail = {},

		NERDTreeGitStatusDirDirty = {},
		NERDTreeGitStatusModified = {},
		NERDTreeGitStatusRenamed = {},
		NERDTreeGitStatusStaged = {},
		NERDTreeGitStatusUntracked = {},
		NERDTreeClosable = {},
		NERDTreeCWD = {},
		NERDTreeDir = {},
		NERDTreeDirSlash = {},
		NERDTreeExecFile = {},
		NERDTreeFile = {},
		NERDTreeFlags = {},
		NERDTreeHelp = {},
		NERDTreeLinkDir = {},
		NERDTreeLinkFile = {},
		NERDTreeLinkTarget = {},
		NERDTreeOpenable = {},
		NERDTreePart = {},
		NERDTreePartFile = {},
		NERDTreeUp = {},

		markdownBold = { style = "bold" },
		markdownCode = {},
		markdownCodeDelimiter = {},
		markdownError = {},
		markdownH1 = { style = "bold" },
		markdownUrl = { fg = colors.bright_blue },
		markdownFootnote = { link = "TSNote" },
		markdownLinkText = { link = "TSURI" },
		markdownLinkTextDelimiter = { fg = colors.gray4 },
		markdownLinkDelimiter = { fg = colors.gray4 },

		mkdDelimiter = {},
		mkdLineBreak = {},
		mkdListItem = {},
		mkdCodeStart = { fg = colors.fg2 },
		mkdCodeEnd = { fg = colors.fg2 },
		mkdURL = { fg = colors.fg4 },

		NvimTreeFolderName = { fg = colors.fg2 },
		NvimTreeRootFolder = { fg = colors.fg },
		NvimTreeSpecialFile = {},

		TelescopeBorder = { fg = colors.fg3 },
		TelescopePromptBorder = { fg = colors.fg3 },
		TelescopeMatching = {},
		TelescopeSelection = { style = "bold" },
		TelescopeSelectionCaret = { fg = colors.fg },
		TelescopeMultiSelection = { style = "italic" },

		BufferCurrent = { fg = colors.fg, bg = colors.bg },
		BufferCurrentMod = { fg = colors.fg, bg = colors.bg, style = "italic" },
		BufferCurrentSign = { fg = colors.fg, bg = colors.bg },
		BufferVisible = { fg = colors.fg2, bg = colors.bg },
		BufferVisibleMod = { fg = colors.fg2, bg = colors.bg, style = "italic" },
		BufferVisibleSign = { fg = colors.fg2, bg = colors.bg },
		BufferInactive = { fg = colors.fg2, bg = colors.bg_alt },
		BufferInactiveMod = { fg = colors.fg2, bg = colors.bg_alt, style = "italic" },
		BufferInactiveSign = { fg = colors.fg2, bg = colors.bg2 },
}

return M
